In [9]:
import pandas as pd
df= pd.read_csv('students.csv')
print(df)

    ID      Name   Age   Gender          City  Marks             Email  \
0    1       Ram  21.0     Male     Kathmandu   85.0     ram@gmail.com
1    2      Sita  22.0   Female       Pokhara   90.0    sita@gmail.com
2    3    Hari    20.0     male     kathmandu   78.0    hari@gmail.com
3    4      Gita   NaN   Female      Lalitpur   88.0    gita@gmail.com
4    5       Ram  21.0     Male     Kathmandu   85.0     ram@gmail.com
5    6      Anil  19.0        M        Butwal   72.0     anilgmail.com
6    7     Suman  23.0   Female       Pokhara    NaN   suman@gmail.com
7    8    prabin  22.0     male        BUTWAL   95.0  prabin@gmail.com
8    9     Nisha  -5.0   Female     Kathmandu   82.0   nisha@gmail.com
9   10    Bikash  24.0     Male     Kathmandu  105.0  bikash@gmail.com
10  11      Asha  21.0        F       Pokhara   89.0    asha@gmail.com
11  12    Ramesh   NaN     Male      Lalitpur   76.0  ramesh@gmail.com
12  13      Sita  22.0   Female       Pokhara   90.0    sita@gmail.com
13  14     Kiran  20.0  Unknown     Kathmandu   81.0               NaN
14  15    Manish  25.0     Male   kathmandu     74.0  manish@gmail.com

       Join_Date
0     2025-01-10
1     2025-01-12
2     2025-01-15
3     2025-01-18
4     2025-01-10
5     2025-02-01
6     2025-02-05
7     2025-02-10
8     2025-02-12
9     2025-02-15
10    2025-02-18
11    2025-02-20
12    2025-01-12
13    2025-03-01
14  invalid_date

In [10]:
df.isnull()

       ID   Name    Age  Gender   City  Marks  Email  Join_Date
0   False  False  False   False  False  False  False      False
1   False  False  False   False  False  False  False      False
2   False  False  False   False  False  False  False      False
3   False  False   True   False  False  False  False      False
4   False  False  False   False  False  False  False      False
5   False  False  False   False  False  False  False      False
6   False  False  False   False  False   True  False      False
7   False  False  False   False  False  False  False      False
8   False  False  False   False  False  False  False      False
9   False  False  False   False  False  False  False      False
10  False  False  False   False  False  False  False      False
11  False  False   True   False  False  False  False      False
12  False  False  False   False  False  False  False      False
13  False  False  False   False  False  False   True      False
14  False  False  False   False  False  False  False      False

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         15 non-null     int64
 1   Name       15 non-null     str
 2   Age        13 non-null     float64
 3   Gender     15 non-null     str
 4   City       15 non-null     str
 5   Marks      14 non-null     float64
 6   Email      14 non-null     str
 7   Join_Date  15 non-null     str
dtypes: float64(2), int64(1), str(5)
memory usage: 1.1 KB

In [12]:
df.describe()

              ID        Age       Marks
count  15.000000  13.000000   14.000000
mean    8.000000  19.615385   85.000000
std     4.472136   7.577802    8.857852
min     1.000000  -5.000000   72.000000
25%     4.500000  20.000000   78.750000
50%     8.000000  21.000000   85.000000
75%    11.500000  22.000000   89.750000
max    15.000000  25.000000  105.000000

In [30]:
df.loc[df['Age']<0,'Age']=None
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Age']=df['Age'].astype(int)

df['Marks']=df['Marks'].fillna(df['Marks'].mean())

df['Email']=df['Email'].fillna(df['Name'].str.lower()+'@gmail.com')

df['Name']=df['Name'].str.strip().str.title()

df['City']=df['City'].str.strip().str.title()
print(df)

    ID    Name  Age Gender       City  Marks             Email   Join_Date
0    1     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
1    2    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
2    3    Hari   20      M  Kathmandu   78.0    hari@gmail.com  2025-01-15
3    4    Gita   21      F   Lalitpur   88.0    gita@gmail.com  2025-01-18
4    5     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
6    7   Suman   23      F    Pokhara   85.0   suman@gmail.com  2025-02-05
7    8  Prabin   22      M     Butwal   95.0  prabin@gmail.com  2025-02-10
8    9   Nisha   21      F  Kathmandu   82.0   nisha@gmail.com  2025-02-12
9   10  Bikash   24      M  Kathmandu  105.0  bikash@gmail.com  2025-02-15
10  11    Asha   21      F    Pokhara   89.0    asha@gmail.com  2025-02-18
11  12  Ramesh   21      M   Lalitpur   76.0  ramesh@gmail.com  2025-02-20
12  13    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
13  14   Kiran   20      M  Kathmandu   81.0   kiran@gmail.com  2025-03-01

In [31]:
df['Gender']=df['Gender'].replace({
    'Male': 'M',
    'Female': 'F',
    'male' : 'M',
    'female' : 'F',
    'Unknown' :'M'
})
print(df)

    ID    Name  Age Gender       City  Marks             Email   Join_Date
0    1     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
1    2    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
2    3    Hari   20      M  Kathmandu   78.0    hari@gmail.com  2025-01-15
3    4    Gita   21      F   Lalitpur   88.0    gita@gmail.com  2025-01-18
4    5     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
6    7   Suman   23      F    Pokhara   85.0   suman@gmail.com  2025-02-05
7    8  Prabin   22      M     Butwal   95.0  prabin@gmail.com  2025-02-10
8    9   Nisha   21      F  Kathmandu   82.0   nisha@gmail.com  2025-02-12
9   10  Bikash   24      M  Kathmandu  105.0  bikash@gmail.com  2025-02-15
10  11    Asha   21      F    Pokhara   89.0    asha@gmail.com  2025-02-18
11  12  Ramesh   21      M   Lalitpur   76.0  ramesh@gmail.com  2025-02-20
12  13    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
13  14   Kiran   20      M  Kathmandu   81.0   kiran@gmail.com  2025-03-01

In [32]:
print("Duplicate rows:",df.duplicated().sum())
# since id is different for all there is no  any duplicates

Duplicate rows: 0

In [33]:
# To drop duplicate 

# df=df.drop_duplicates(subset=['Name']).reset_index(drop=True)
# print(df)

In [34]:
df= df[df['Email'].str.contains('@', na=False)]
df= df.dropna()
print(df)

    ID    Name  Age Gender       City  Marks             Email   Join_Date
0    1     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
1    2    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
2    3    Hari   20      M  Kathmandu   78.0    hari@gmail.com  2025-01-15
3    4    Gita   21      F   Lalitpur   88.0    gita@gmail.com  2025-01-18
4    5     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
6    7   Suman   23      F    Pokhara   85.0   suman@gmail.com  2025-02-05
7    8  Prabin   22      M     Butwal   95.0  prabin@gmail.com  2025-02-10
8    9   Nisha   21      F  Kathmandu   82.0   nisha@gmail.com  2025-02-12
9   10  Bikash   24      M  Kathmandu  105.0  bikash@gmail.com  2025-02-15
10  11    Asha   21      F    Pokhara   89.0    asha@gmail.com  2025-02-18
11  12  Ramesh   21      M   Lalitpur   76.0  ramesh@gmail.com  2025-02-20
12  13    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
13  14   Kiran   20      M  Kathmandu   81.0   kiran@gmail.com  2025-03-01

In [35]:
df= df[pd.to_datetime(df['Join_Date'],errors='coerce').notna()]
print(df)

    ID    Name  Age Gender       City  Marks             Email   Join_Date
0    1     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
1    2    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
2    3    Hari   20      M  Kathmandu   78.0    hari@gmail.com  2025-01-15
3    4    Gita   21      F   Lalitpur   88.0    gita@gmail.com  2025-01-18
4    5     Ram   21      M  Kathmandu   85.0     ram@gmail.com  2025-01-10
6    7   Suman   23      F    Pokhara   85.0   suman@gmail.com  2025-02-05
7    8  Prabin   22      M     Butwal   95.0  prabin@gmail.com  2025-02-10
8    9   Nisha   21      F  Kathmandu   82.0   nisha@gmail.com  2025-02-12
9   10  Bikash   24      M  Kathmandu  105.0  bikash@gmail.com  2025-02-15
10  11    Asha   21      F    Pokhara   89.0    asha@gmail.com  2025-02-18
11  12  Ramesh   21      M   Lalitpur   76.0  ramesh@gmail.com  2025-02-20
12  13    Sita   22      F    Pokhara   90.0    sita@gmail.com  2025-01-12
13  14   Kiran   20      M  Kathmandu   81.0   kiran@gmail.com  2025-03-01

In [36]:
df.to_csv('Cleaned_Student_Data',index=True)